name: Windows build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./bnbnav-frontend
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Run qmake
      run: qmake bnbnav-frontend.pro
    - name: Build
      run: nmake
    - name: Prepare for deployment
      run: |
        mkdir bnbnav-win
        cp release/bnbnav-frontend.exe bnbnav-win
    - name: Deploy
      run: windeployqt bnbnav-win
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: bnbnav-win
        path: bnbnav-frontend/bnbnav-win
